name 'powers-jenkins'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures powers-jenkins'
long_description 'Installs/Configures powers-jenkins'
version '0.1.1'
depends 'jenkins'
